steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/link-saver", "."]
    # push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/link-saver"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "link-saver",
        "--image",
        "gcr.io/$PROJECT_ID/link-saver",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--update-env-vars",
        "API_KEY=${_API_KEY},DB_URL=${_DB_URL},DB_SSL=${_DB_SSL}",
      ]
images:
  - gcr.io/$PROJECT_ID/link-saver
